import path from "path";
import fs from "fs-extra";
import { writeStoryTestsFile } from "./write-tests-file";
import { buildStoryTestFiles, getStoryFile } from "./index";
import { StorybookStoryExtended } from "../get-stories";
import type { Test } from "testplane";

jest.mock("os", () => ({ tmpdir: jest.fn().mockReturnValue("/tmpdir") }));
jest.mock("fs-extra");
jest.mock("./write-tests-file");

describe("storybook/story-to-test", () => {
    afterEach(() => {
        jest.restoreAllMocks();
    });

    describe("buildStoryTestFiles", () => {
        it("should save tests in tmpdir", async () => {
            const story = { importPath: "./story/path/story.js" } as StorybookStoryExtended;

            const storyTestFiles = await buildStoryTestFiles([story], {
                autoScreenshots: true,
                autoscreenshotSelector: "foobar",
                autoScreenshotStorybookGlobals: {},
            });

            expect(storyTestFiles).toEqual([
                "/tmpdir/testplane-storybook-autogenerated/story/path/story.js.testplane.js",
            ]);
        });

        it("should empty tests dir before writing tests", async () => {
            await buildStoryTestFiles([], {
                autoScreenshots: true,
                autoscreenshotSelector: "foobar",
                autoScreenshotStorybookGlobals: {},
            });

            expect(fs.emptyDir).toBeCalled();
        });

        it("should write test files for given stories", async () => {
            jest.spyOn(path, "resolve").mockImplementation((_, storyPath) => storyPath);
            const storyFirst = { importPath: "./story/path/story-first.js" } as StorybookStoryExtended;
            const storySecond = { importPath: "./story/path/story-second.js" } as StorybookStoryExtended;
            const opts = {
                autoScreenshots: true,
                autoscreenshotSelector: "foobar",
                autoScreenshotStorybookGlobals: { foo: { bar: "baz" } },
            };

            const storyTestFiles = await buildStoryTestFiles([storyFirst, storySecond], opts);

            expect(writeStoryTestsFile).toBeCalledWith({
                testFile: "./story/path/story-first.js.testplane.js",
                stories: [storyFirst],
                opts,
            });

            expect(writeStoryTestsFile).toBeCalledWith({
                testFile: "./story/path/story-second.js.testplane.js",
                stories: [storySecond],
                opts,
            });

            expect(storyTestFiles).toEqual([
                "./story/path/story-first.js.testplane.js",
                "./story/path/story-second.js.testplane.js",
            ]);
        });

        it("should encode '../' in story importPath when building test file path", async () => {
            const story = { importPath: "../outside/story.js" } as StorybookStoryExtended;

            const storyTestFiles = await buildStoryTestFiles([story], {
                autoScreenshots: true,
                autoscreenshotSelector: "foobar",
                autoScreenshotStorybookGlobals: {},
            });

            expect(storyTestFiles).toEqual([
                "/tmpdir/testplane-storybook-autogenerated/_TP-SB-BACK_/outside/story.js.testplane.js",
            ]);
        });

        it("should encode '/../' in the middle of story importPath", async () => {
            const story = { importPath: "./foo/../bar/story.js" } as StorybookStoryExtended;

            const storyTestFiles = await buildStoryTestFiles([story], {
                autoScreenshots: true,
                autoscreenshotSelector: "foobar",
                autoScreenshotStorybookGlobals: {},
            });

            expect(storyTestFiles).toEqual([
                "/tmpdir/testplane-storybook-autogenerated/foo/_TP-SB-BACK_/bar/story.js.testplane.js",
            ]);
        });
    });

    describe("getStoryFile", () => {
        it("should return decoded story file path from test file", () => {
            const test = {
                file: "/tmpdir/testplane-storybook-autogenerated/story/path/story.js.testplane.js",
                fullTitle: () => "test title",
            } as unknown as Test;

            expect(getStoryFile(test)).toBe("story/path/story.js");
        });

        it("should decode encoded '../' back to original path", () => {
            const test = {
                file: "/tmpdir/testplane-storybook-autogenerated/_TP-SB-BACK_/outside/story.js.testplane.js",
                fullTitle: () => "test title",
            } as unknown as Test;

            expect(getStoryFile(test)).toBe("../outside/story.js");
        });

        it("should decode encoded '/../' in the middle back to original path", () => {
            const test = {
                file: "/tmpdir/testplane-storybook-autogenerated/foo/_TP-SB-BACK_/bar/story.js.testplane.js",
                fullTitle: () => "test title",
            } as unknown as Test;

            expect(getStoryFile(test)).toBe("foo/../bar/story.js");
        });

        it("should throw if test file is not in storybook tmp dir", () => {
            const test = {
                file: "/some/other/path/story.js.testplane.js",
                fullTitle: () => "test title",
            } as unknown as Test;

            expect(() => getStoryFile(test)).toThrow("Can't get storyfile");
        });

        it("should throw if test file does not end with testplane suffix", () => {
            const test = {
                file: "/tmpdir/testplane-storybook-autogenerated/story/path/story.js",
                fullTitle: () => "test title",
            } as unknown as Test;

            expect(() => getStoryFile(test)).toThrow("Can't get storyfile");
        });
    });
});
