export const STORYBOOK_JSON_SUPPORTED_VERSIONS = [3, 4];
export const STORYBOOK_WAIT_SERVER_TIMEOUT = 30000;
export const STORYBOOK_SERVER_REQUEST_TIMEOUT = 10000;
export const STORYBOOK_SERVER_CHECK_INTERVAL = 5000;

export const STORYBOOK_TEST_DIRNAME = "hermione-storybook-autogenerated";
export const STORYBOOK_SET_NAME = "hermione-storybook-autogenerated";

export const STORYBOOK_INDEX_PATH = "index.html";
export const STORYBOOK_IFRAME_PATH = "iframe.html";
export const STORYBOOK_INDEX_JSON_PATH = "index.json"; // storybook@7, json v4
export const STORYBOOK_STORIES_JSON_PATH = "stories.json"; // storybook@6, json v3
export const STORYBOOK_KNOWN_PATH_ENDINGS = [
    STORYBOOK_INDEX_PATH,
    STORYBOOK_IFRAME_PATH,
    STORYBOOK_INDEX_JSON_PATH,
    STORYBOOK_STORIES_JSON_PATH,
];
